# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "building"
        - npm install

    artifacts:
        paths:
            - node_modules/

test:
    stage: test
    script:
        - echo "testing"
        - node index.js

